services:
  frontend:
    container_name: duyeet-frontend
    build: frontend/
    environment:
      - PORT=8000
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    container_name: duyeet-backend
    build: backend/
    environment:
      - PORT=8001
      - DATABASE=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_USER_PASSWORD=postgres
      - DATABASE_NAME=duyeet
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - database

  database:
    container_name: duyeet-database
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=duyeet
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database:
    driver: local
