services:
  frontend:
    container_name: duyeet-frontend
    build: frontend/
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "8000:8000"

  backend:
    container_name: duyeet-backend
    build: backend/
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - "8001:8001"
