# Details at https://golangci-lint.run/usage/configuration/#config-file

# Options for analysis running.
run:
  # See the dedicated "run" documentation section.

# output configuration options
output:
  # See the dedicated "output" documentation section.

# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.

linters:
  # See the dedicated "linters" documentation section.

issues:
  # See the dedicated "issues" documentation section.

severity:
  # See the dedicated "severity" documentation section.
